import colors from "./colors";

const screens = {
  ONBOARD: "ONBOARD",
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  HOME: "HOME",
  PROFILE_COMPLETE:'PROFILE_COMPLETE',
  WELCOME: 'WELCOME',
  DASHBOARD: 'DASHBOARD',
  WORKOUT_TRACKER: 'WORKOUT_TRACKER',
  WORKOUT_DETAIL: 'WORKOUT_DETAIL',
  WORKOUT_ROUITINE: 'WORKOUT_ROUITINE',
  MANAGE_EXERCICES: 'MANAGE_EXERCICES',
  ADD_EXERCISES: 'ADD_EXERCISES',
  ADD_CUSTOME_WORKOUT: 'ADD_CUSTOME_WORKOUT',
  EXERCISE: 'EXERCISE',
  PROFILE: 'PROFILE',
  NOTIFICATION : 'NOTIFICATION',
  MEALPLANNER : 'MEALPLANNER',
  ADDMEAL : 'ADDMEAL'
};

export { colors, screens };
