import colors from "./colors";

const screens = {
  ONBOARD: "ONBOARD",
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  HOME: "HOME",
  PROFILE_COMPLETE:'PROFILE_COMPLETE',
  WELCOME: 'WELCOME',
  DASHBOARD: 'DASHBOARD',
  WORKOUT_TRACKER: 'WORKOUT_TRACKER',
  WORKOUT_DETAIL: 'WORKOUT_DETAIL',
  WORKOUT_ROUITINE: 'WORKOUT_ROUITINE'
};

export { colors, screens };
